_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/dominika/mikele/rcnn_tracker/pretrained/mask_rcnn_R_50_FPN_3x_original/model_final_f10217.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 10000
