_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/home/magister/magisterka/rcnn_tracker/pretrained/mask_rcnn_R_101_FPN_3x_original/model_final_a3ec72.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
