_BASE_: "Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "/home/magister/magisterka/rcnn_tracker/pretrained/mask_rcnn_R_50_C4_3x_original/model_final_4ce675.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
